// Layer 9 — Project Lifecycle phase definitions.

export interface LifecyclePhaseDef {
  key: string;
  name: string;
  order: number;
  objectives: string[];
  deliverables: string[]; // template keys where applicable
  exitCriteria: string[];
  risks: string[];
  kpis: string[];
}

export const LIFECYCLE_PHASES: LifecyclePhaseDef[] = [
  {
    key: "sales",
    name: "Sales",
    order: 1,
    objectives: ["Qualify opportunity", "Align on scope and value hypothesis", "Secure sponsorship"],
    deliverables: ["proposal"],
    exitCriteria: ["Signed SOW or engagement letter", "Executive sponsor identified", "Budget confirmed"],
    risks: ["Unclear sponsor", "Scope ambiguity", "Unrealistic expectations"],
    kpis: ["Win rate", "Time to close"],
  },
  {
    key: "discovery",
    name: "Discovery",
    order: 2,
    objectives: ["Understand real business problem", "Map current state", "Identify stakeholders and constraints"],
    deliverables: ["meeting-minutes", "stakeholder-register", "raid-log", "workshop-notes"],
    exitCriteria: ["Problem statement signed off", "Discovery brief complete", "Stakeholder register complete"],
    risks: ["Wrong problem framing", "Missing stakeholders", "Hidden constraints"],
    kpis: ["Stakeholder coverage", "Discovery cycle time"],
  },
  {
    key: "assessment",
    name: "Assessment",
    order: 3,
    objectives: ["Assess AI readiness", "Quantify gaps", "Validate feasibility"],
    deliverables: ["ai-readiness-report", "gap-analysis", "swot"],
    exitCriteria: ["Readiness report accepted", "Go/no-go decision documented"],
    risks: ["Data quality worse than assumed", "Talent gaps", "Shadow IT"],
    kpis: ["Readiness score", "Gaps identified vs closed"],
  },
  {
    key: "strategy",
    name: "Strategy",
    order: 4,
    objectives: ["Prioritize use cases", "Define roadmap and business case", "Set governance foundations"],
    deliverables: ["recommendations-report", "governance-charter"],
    exitCriteria: ["Roadmap approved by steering committee", "Business case signed off"],
    risks: ["Prioritization politics", "ROI overestimation"],
    kpis: ["Approved use cases", "Projected ROI"],
  },
  {
    key: "architecture",
    name: "Architecture",
    order: 5,
    objectives: ["Design target solution architecture", "Select technology stack", "Design security and data flows"],
    deliverables: ["solution-design", "security-design", "api-design"],
    exitCriteria: ["Architecture review board approval", "Security sign-off"],
    risks: ["Integration complexity underestimated", "Vendor lock-in", "Security gaps"],
    kpis: ["Review findings closed", "NFR coverage"],
  },
  {
    key: "pilot",
    name: "Pilot",
    order: 6,
    objectives: ["Prove value on narrow scope", "Validate technical assumptions", "Measure baseline vs pilot KPIs"],
    deliverables: ["test-plan"],
    exitCriteria: ["Pilot success criteria met", "Stakeholder demo delivered", "Scale decision made"],
    risks: ["Pilot-to-production gap", "Cherry-picked scope"],
    kpis: ["Pilot KPI delta", "User feedback score"],
  },
  {
    key: "mvp",
    name: "MVP",
    order: 7,
    objectives: ["Ship minimum production-grade slice", "Establish MLOps/LLMOps pipeline", "Onboard first real users"],
    deliverables: ["project-plan", "sprint-plan"],
    exitCriteria: ["MVP live with real users", "Monitoring in place", "Guardrails validated"],
    risks: ["Scope creep", "Production hardening skipped"],
    kpis: ["Time to MVP", "Adoption rate"],
  },
  {
    key: "implementation",
    name: "Implementation",
    order: 8,
    objectives: ["Build full solution", "Integrate with enterprise systems", "Harden security and guardrails"],
    deliverables: ["project-plan", "sprint-plan", "api-design"],
    exitCriteria: ["All planned features complete", "Integration tests passing", "Security review passed"],
    risks: ["Integration delays", "Key person dependency", "Model quality regression"],
    kpis: ["Velocity", "Defect rate", "Milestone adherence"],
  },
  {
    key: "testing",
    name: "Testing",
    order: 9,
    objectives: ["Validate functional and non-functional requirements", "Run UAT", "Red-team AI behavior"],
    deliverables: ["test-plan", "uat-plan"],
    exitCriteria: ["UAT signed off", "Critical defects zero", "AI eval scores above threshold"],
    risks: ["Inadequate AI evals", "UAT fatigue"],
    kpis: ["Test coverage", "Eval pass rate", "Defect escape rate"],
  },
  {
    key: "deployment",
    name: "Deployment",
    order: 10,
    objectives: ["Release to production", "Establish rollback and monitoring", "Communicate go-live"],
    deliverables: ["sop", "runbook"],
    exitCriteria: ["Production deployment stable", "Runbook accepted by ops", "Rollback tested"],
    risks: ["Deployment failure", "Monitoring blind spots"],
    kpis: ["Deployment success rate", "MTTR"],
  },
  {
    key: "training",
    name: "Training",
    order: 11,
    objectives: ["Enable end users and admins", "Transfer knowledge to client team"],
    deliverables: ["training-plan"],
    exitCriteria: ["Training completion targets met", "Admin team certified"],
    risks: ["Low adoption", "Knowledge concentrated in consultants"],
    kpis: ["Training completion", "Adoption rate post-training"],
  },
  {
    key: "hypercare",
    name: "Hypercare",
    order: 12,
    objectives: ["Intensive post-go-live support", "Rapid defect resolution", "Stabilize operations"],
    deliverables: ["runbook"],
    exitCriteria: ["Incident rate below threshold for 2 weeks", "Handover to managed services complete"],
    risks: ["Unresolved defects at exit", "Support team unprepared"],
    kpis: ["Incident volume trend", "Resolution SLA compliance"],
  },
  {
    key: "managed-services",
    name: "Managed Services",
    order: 13,
    objectives: ["Ongoing operations per SLA", "Model/prompt maintenance", "Cost management"],
    deliverables: ["sla", "monitoring-plan"],
    exitCriteria: ["SLA consistently met quarter over quarter"],
    risks: ["Model drift", "Cost overrun", "Stale knowledge base"],
    kpis: ["SLA compliance", "Cost per query", "Model quality score"],
  },
  {
    key: "continuous-improvement",
    name: "Continuous Improvement",
    order: 14,
    objectives: ["Measure business impact", "Expand use cases", "Feed lessons learned back"],
    deliverables: ["ci-report"],
    exitCriteria: ["Quarterly improvement review held", "Lessons learned captured"],
    risks: ["Stagnation after go-live", "No ownership of improvements"],
    kpis: ["ROI realized", "User satisfaction", "New use cases launched"],
  },
];
