// Demo mode: deterministic rule-based engine used when ANTHROPIC_API_KEY is
// not configured. Produces structured outputs from the seeded knowledge base
// so the full engagement flow works without an LLM. Real AI takes over
// automatically once a key is set.

import { TAXONOMY } from "@/lib/knowledge/taxonomy";
import { AI_USE_CASES } from "@/lib/knowledge/use-cases";
import { INDUSTRY_ACCELERATORS } from "@/lib/knowledge/accelerators";
import { REFERENCE_ARCHITECTURES } from "@/lib/knowledge/reference-architectures";
import { DELIVERABLE_TEMPLATES } from "@/lib/knowledge/deliverable-templates";
import type { Brief, Classification, Recommendation, Architecture } from "@/lib/ai/schemas";

export const isDemoMode = () => !process.env.ANTHROPIC_API_KEY;

const DEMO_NOTE = "_[Demo mode — generated by the rule engine without AI. Add ANTHROPIC_API_KEY for full AI generation.]_";

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

// ---------- Discovery interview (scripted McKinsey question ladder) ----------

const QUESTION_LADDER = [
  "Thank you for that context. Let's dig into the underlying problem: what does the current workflow look like end-to-end, and where exactly does it break down? Please quantify where you can — volumes, cycle times, error rates, cost.",
  "Helpful. Now on systems and data: which systems are involved (ERP, CRM, document stores, email), and where does the critical data live today? Any data quality concerns?",
  "Understood. What would success look like in 12 months? Which KPIs must move, and by how much? And who are the key stakeholders — sponsor, process owners, IT, compliance?",
  "Two final areas: first, constraints — budget range, timeline expectations, compliance or security requirements (PII, regulations, data residency)? Second, why AI specifically, and why now?",
  "I believe we have enough for a solid engagement brief. Click **Complete discovery** to extract the structured brief, then proceed to Classification. If anything important is missing, add it here first.",
];

export function demoDiscoveryReply(messages: ChatMessage[]): string {
  const userTurns = messages.filter((m) => m.role === "user").length;
  const idx = Math.min(userTurns - 1, QUESTION_LADDER.length - 1);
  return `${QUESTION_LADDER[idx]}\n\n${DEMO_NOTE}`;
}

// ---------- Brief extraction ----------

function firstSentences(text: string, n: number): string {
  return text.split(/(?<=[.!?])\s+/).slice(0, n).join(" ");
}

export function demoBrief(messages: ChatMessage[]): Brief {
  const userText = messages.filter((m) => m.role === "user").map((m) => m.content).join("\n");
  const grab = (re: RegExp) => userText.match(re)?.[0] ?? "Not yet discussed";

  return {
    problemStatement: firstSentences(userText, 2) || "Not yet discussed",
    currentState: firstSentences(userText, 4) || "Not yet discussed",
    futureState: "Target state to be refined in assessment. " + DEMO_NOTE,
    businessObjectives: ["Reduce cycle time", "Reduce manual effort", "Improve quality/accuracy"],
    constraints: ["To be validated in assessment"],
    successMetrics: ["Cycle time", "Straight-through processing rate", "Error rate", "User satisfaction"],
    stakeholders: [grab(/\b(CIO|CEO|CFO|COO|CTO|sponsor|director|head of \w+)\b/i)],
    timeline: grab(/\b\d+\s*(months?|weeks?|quarters?|years?)\b/i),
    budget: grab(/\$\s?[\d,.]+\s?[kKmM]?|\b\d+k\b/),
    compliance: /pii|gdpr|hipaa|regulat|complian/i.test(userText)
      ? ["Compliance requirements mentioned — detail in assessment"]
      : ["Not yet discussed"],
    whyAI: "Manual, repetitive, document/data-heavy work identified as automation candidate. " + DEMO_NOTE,
  };
}

// ---------- Classification (keyword scoring against taxonomy) ----------

export function demoClassify(text: string): Classification {
  const lower = text.toLowerCase();
  let best = TAXONOMY[0];
  let bestScore = -1;
  for (const d of TAXONOMY) {
    const terms = [d.domain, ...d.subDomains].join(" ").toLowerCase().split(/[^a-z]+/);
    const score = [...new Set(terms)].filter((t) => t.length > 3 && lower.includes(t)).length;
    if (score > bestScore) {
      bestScore = score;
      best = d;
    }
  }
  const subDomain =
    best.subDomains.find((s) =>
      s.toLowerCase().split(/[^a-z]+/).some((t) => t.length > 3 && lower.includes(t))
    ) ?? best.subDomains[0];

  const painPoints = [
    ...(/manual|re-?key|swivel/i.test(text) ? ["Manual data entry / re-keying"] : []),
    ...(/backlog|cycle time|slow|delay/i.test(text) ? ["Long cycle times / backlog"] : []),
    ...(/error|defect|quality|rework/i.test(text) ? ["Error rates / rework"] : []),
    ...(/cost|expensive|budget/i.test(text) ? ["High processing cost"] : []),
  ];

  return {
    domain: best.domain,
    subDomain,
    businessFunction: "Operations",
    painPoints: painPoints.length ? painPoints : ["Manual effort", "Process inefficiency"],
    opportunityAreas: best.typicalUseCases
      .map((k) => AI_USE_CASES.find((u) => u.key === k)?.name ?? k)
      .slice(0, 3),
    issueTree: {
      label: `Why is ${best.domain.toLowerCase()} underperforming?`,
      children: [
        {
          label: "Process drivers",
          children: [{ label: "Manual handoffs and re-keying" }, { label: "No straight-through processing" }],
        },
        {
          label: "Technology drivers",
          children: [{ label: "Legacy systems without automation hooks" }, { label: "Unstructured data locked in documents" }],
        },
        {
          label: "Organizational drivers",
          children: [{ label: "Skills and change readiness" }, { label: "Governance and ownership gaps" }],
        },
      ],
    },
  };
}

// ---------- Recommendations (rule-based from knowledge base) ----------

export function demoRecommend(domain: string, industry: string): Recommendation {
  const taxonomyEntry = TAXONOMY.find((t) => t.domain === domain) ?? TAXONOMY[0];
  const accel =
    INDUSTRY_ACCELERATORS.find((a) => a.name.toLowerCase() === industry.toLowerCase()) ??
    INDUSTRY_ACCELERATORS.find((a) => industry.toLowerCase().includes(a.key)) ??
    INDUSTRY_ACCELERATORS[0];

  return {
    methodologies: [
      { key: "seven-step", rationale: "Backbone for structuring the problem end-to-end.", priority: 1 },
      { key: "mece-issue-tree", rationale: "Decompose the problem space before solutioning.", priority: 2 },
      { key: "as-is-to-be", rationale: "Document current process and design the AI-enabled future state.", priority: 3 },
      { key: "ai-readiness", rationale: "Validate data, infrastructure, and talent before committing.", priority: 4 },
      { key: "ai-governance", rationale: "Mandatory for production AI — establishes controls and accountability.", priority: 5 },
    ],
    useCases: taxonomyEntry.typicalUseCases.slice(0, 3).map((key, i) => ({
      key,
      rationale: `Standard fit for ${taxonomyEntry.domain} problems per the firm knowledge base. ${DEMO_NOTE}`,
      confidence: 80 - i * 15,
    })),
    acceleratorKey: accel.key,
    acceleratorRationale: `Matched on engagement industry (${industry}). Brings regulations, reference architectures, and KPI benchmarks.`,
    team: [
      { role: "Engagement Lead", rationale: "Owns client relationship and problem structuring." },
      { role: "AI Solution Architect", rationale: "Designs target architecture and guardrails." },
      { role: "Business Analyst", rationale: "Process mapping, requirements, and UAT." },
      { role: "ML/LLM Engineer", rationale: "Builds and evaluates the AI pipeline." },
    ],
    risks: [
      { risk: "Data quality below expectations", category: "Data", mitigation: "Early data profiling in assessment phase" },
      { risk: "User adoption resistance", category: "Change", mitigation: "Early stakeholder engagement and training plan" },
      { risk: "Integration complexity with legacy systems", category: "Technical", mitigation: "Architecture spike in pilot phase" },
      { risk: "Regulatory/compliance gaps", category: "Compliance", mitigation: "Governance checklist and compliance review per phase" },
    ],
    notRecommended: [
      { option: "fine-tuning", rationale: "Prompting + retrieval typically sufficient; fine-tuning adds cost and maintenance before value is proven." },
      { option: "multi-agent", rationale: "Start with a single well-guarded workflow; multi-agent orchestration is premature at this stage." },
    ],
  };
}

// ---------- Architecture (reference pattern match) ----------

export function demoArchitecture(useCaseKeys: string[]): Architecture {
  const ref =
    (useCaseKeys.includes("document-ai") || useCaseKeys.includes("ocr")
      ? REFERENCE_ARCHITECTURES.find((r) => r.key === "document-ai")
      : useCaseKeys.includes("ai-agent")
        ? REFERENCE_ARCHITECTURES.find((r) => r.key === "customer-service-agent")
        : REFERENCE_ARCHITECTURES.find((r) => r.key === "rag-pipeline")) ?? REFERENCE_ARCHITECTURES[0];

  return {
    summary: `Reference architecture based on the firm's "${ref.name}" pattern, selected to match the recommended use cases. Includes guardrails, human oversight, and audit logging by default. ${DEMO_NOTE}`,
    components: ref.components.map((name) => ({
      name,
      responsibility: `${name} — see firm reference pattern "${ref.name}".`,
    })),
    dataFlow: [
      "Input captured from source channel",
      "Content extracted and normalized",
      "AI processing with guardrails applied",
      "Low-confidence cases routed to human review",
      "Results written to system of record with audit trail",
    ],
    techStack: ["LLM Gateway", "Vector Database", "Embeddings", "API", "Observability", "CI/CD"],
    mermaidDiagram: ref.mermaid,
  };
}

// ---------- Deliverable (template skeleton) ----------

export function demoDeliverable(templateKey: string, context: string): string {
  const template = DELIVERABLE_TEMPLATES.find((t) => t.key === templateKey)!;
  const sections = template.structure
    .map((s) => `## ${s}\n\n[TBD — complete this section. Relevant engagement context below.]\n`)
    .join("\n");
  return `# ${template.name}\n\n> ${DEMO_NOTE}\n\n${sections}\n---\n\n### Engagement context (auto-attached)\n\n\`\`\`\n${context}\n\`\`\`\n`;
}
